default:
	g++ -std=c++0x -fopenmp -O3\
    main.cpp         \
    ../../vmcsolver/VMCWrapper.cpp      \
    ../../vmcsolver/VMCSolver.cpp       \
    ../../vmcsolver/VMCSolverGto.cpp       \
    ../../vmcsolver/VMCSolverGtoI.cpp       \
    ../../CPhys/CPhys.cpp  \
    ../../CPhys/Vector.cpp \
    ../../CPhys/Matrix.cpp \
    ../../CPhys/Cube.cpp   
