main:
	g++ VMCSolver.cpp main.cpp ../CPhys/CPhys.cpp  \
		../CPhys/Vector.cpp ../CPhys/Matrix.cpp ../CPhys/Cube.cpp 
param:
	g++ VMCSolver.cpp parameters.cpp ../CPhys/CPhys.cpp  \
		../CPhys/Vector.cpp ../CPhys/Matrix.cpp ../CPhys/Cube.cpp 
