main:
	g++ -std=c++0x -fopenmp \
    VMCWrapper.cpp      \
    VMCSolver.cpp       \
    main.cpp            \
    ../CPhys/CPhys.cpp  \
    ../CPhys/Vector.cpp \
    ../CPhys/Matrix.cpp \
    ../CPhys/Cube.cpp 
