default:
	g++ -std=c++0x -fopenmp \
    $(cpp_file)         \
    ../../vmcsolver/VMCWrapper.cpp      \
    ../../vmcsolver/VMCSolver.cpp       \
    ../../CPhys/CPhys.cpp  \
    ../../CPhys/Vector.cpp \
    ../../CPhys/Matrix.cpp \
    ../../CPhys/Cube.cpp   
	
