compile:
	g++ --std=c++0x -fopenmp    \
    main.cpp                    \
    ../vmcsolver/VMCWrapper.cpp \
    ../vmcsolver/VMCSolver.cpp  \
    ../CPhys/CPhys.cpp          \
    ../CPhys/Vector.cpp         \
    ../CPhys/Matrix.cpp         \
    ../CPhys/Cube.cpp           \
    -lunittest++
