main:
	g++ VMCSolver.cpp main.cpp ../CPhys/CPhys.a -O3
param:
	g++ VMCSolver.cpp parameters.cpp ../CPhys/CPhys.a -O3
heliumWave1Alpha:
	g++ VMCSolver.cpp plotDataHeliumWave1Alpha.cpp ../CPhys/CPhys.a -O3
heliumWave2Beta:
	g++ VMCSolver.cpp plotDataHeliumWave2Beta.cpp ../CPhys/CPhys.a -O3
heliumWave2Alpha:
	g++ VMCSolver.cpp plotDataHeliumWave2Alpha.cpp ../CPhys/CPhys.a -O3
