main:
	g++ VMCSolver.cpp main.cpp ../CPhys/CPhys.a -O3
param:
	g++ VMCSolver.cpp parameters.cpp ../CPhys/CPhys.a -O3
heliumWave1Alpha:
	g++ VMCSolver.cpp heliumWave1Alpha.cpp ../CPhys/CPhys.a -O3
heliumWave2Beta:
	g++ VMCSolver.cpp heliumWave2Beta.cpp ../CPhys/CPhys.a -O3
heliumWave2Alpha:
	g++ VMCSolver.cpp heliumWave2Alpha.cpp ../CPhys/CPhys.a -O3
heliumWave1Wave2:
	g++ VMCSolver.cpp heliumWave1Wave2.cpp ../CPhys/CPhys.a -O3
heliumWave2Local:
	g++ VMCSolver.cpp heliumWave2Local.cpp ../CPhys/CPhys.a -O3
heliumWave2Importance:
	g++ VMCSolver.cpp heliumWave2Importance.cpp ../CPhys/CPhys.a -O3
heliumWave1Wave2Density:
	g++ VMCSolver.cpp heliumWave1Wave2Density.cpp ../CPhys/CPhys.a -O3
